### ISSUE TITLE
Crash on settings

### ISSUE THREAD

**Issue by Jacoblightning** [Alberto97/OUILookup#356]
I'm on the latest version with the settings crash patch and it still crashes for me. I have a log of the crash: 

`FATAL EXCEPTION: main
Process: org.alberto97.ouilookup, PID: 16796
E2.B: lateinit property useDynamicTheme has not been initialized
	at r2.a.a(SourceFile:113)
	at Z2.m.h(SourceFile:66)
	at N.b.b(SourceFile:44)
	at N.b.h(SourceFile:9)
	at D.i0.l(SourceFile:308)
	at N.b.l(SourceFile:52)
	at k.I.u(SourceFile:5)
	at F.r.a(SourceFile:218)
	at O.h.d(SourceFile:96)
	at p.N.d(SourceFile:59)
	at p1.n.l(SourceFile:63)
	at N.b.l(SourceFile:52)
	at k.I.u(SourceFile:5)
	at F.r.b(SourceFile:146)
	at p.N.c(SourceFile:58)
	at p1.r.h(SourceFile:72)
	at N.b.b(SourceFile:44)
	at N.b.h(SourceFile:9)
	at k.f.k(SourceFile:416)
	at N.b.a(SourceFile:44)
	at N.b.k(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:130)
	at k.g.l(SourceFile:272)
	at N.b.l(SourceFile:52)
	at K1.f.a(SourceFile:73)
	at p.v.c(SourceFile:130)
	at p1.u.l(SourceFile:120)
	at F.p.G(SourceFile:483)
	at F.p.N(SourceFile:58)
	at F.p.r(SourceFile:158)
	at F.p.E(SourceFile:29)
	at F.w.v(SourceFile:35)
	at F.x0.s(SourceFile:114)
	at F.v0.o(SourceFile:377)
	at n0.V.doFrame(SourceFile:7)
	at n0.T.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1397)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
	at android.view.Choreographer.doFrame(Choreographer.java:934)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: E2.g: [F.i0@68faa81, n0.u0@1e51726, m0{Cancelling}@8fc9f67, U@ccb7114]`

**Comment by Jacoblightning** [comment]
Never mind, it appears that f-droid thinks that it's latest version it the bugfix even though it's not?![Screenshot_20240711-162142_Trebuchet.png](https://github.com/user-attachments/assets/5b1801f1-c27a-4dab-bfad-d9d354d66ceb)
